import { useState, useEffect } from 'react';
import type { VegaChartSpec } from '../../types/chart';
import type { View } from 'vega';
import LZString from 'lz-string';

interface ChartSpecModalProps {
    isOpen: boolean;
    onClose: () => void;
    chartSpec: VegaChartSpec;
    vegaView?: View | null;
    onApply?: (newSpec: VegaChartSpec) => void;
    aiGeneratedSpec?: VegaChartSpec; // Original spec generated by AI
}

// Helper function to move 'data' property to the end of the object and hide values
function moveDataToEnd(spec: VegaChartSpec, hideValues = true): string {
    const { data, ...rest } = spec;
    if (!data) {
        return JSON.stringify({ ...rest }, null, 2);
    }

    // Remove values from data for display in modal
    if (hideValues && 'values' in data) {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { values, ...dataWithoutValues } = data;
        const specWithoutValues = {
            ...rest,
            data: dataWithoutValues,
        };
        return JSON.stringify(specWithoutValues, null, 2);
    }

    return JSON.stringify({ ...rest, data }, null, 2);
}

// Maximum size for data.values in Vega Editor URL (in characters)
// LZ-String compression helps, but we still need to keep this reasonable
const MAX_VALUES_SIZE = 10000;

// Helper function to prepare spec for Vega Editor with size limit
function prepareSpecForVegaEditor(spec: VegaChartSpec, vegaView?: View | null): VegaChartSpec {
    let dataValues: Record<string, unknown>[] = [];

    // Get data from Vega View if available
    if (vegaView) {
        try {
            dataValues = vegaView.data('source_0') || [];
        } catch (err) {
            console.warn('Could not get data from Vega View:', err);
        }
    }

    // Remove all data properties (sql, url, etc.) and add only values
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { data, ...specWithoutData } = spec;

    const editorSpec = {
        ...specWithoutData,
        data: {
            values: dataValues,
        },
    };

    // Check if the spec is too large
    const specString = JSON.stringify(editorSpec);
    if (specString.length > MAX_VALUES_SIZE) {
        // Cut values to fit within size limit
        const overhead = JSON.stringify({ ...editorSpec, data: { values: [] } }).length;
        const availableSize = MAX_VALUES_SIZE - overhead - 100; // -100 for safety margin

        // Calculate how many rows we can include
        const sampleRow = dataValues[0] ? JSON.stringify(dataValues[0]).length : 100;
        const maxRows = Math.max(1, Math.floor(availableSize / sampleRow));
        const limitedValues = dataValues.slice(0, maxRows);

        console.warn(
            `Data too large for Vega Editor (${dataValues.length} rows). Limited to ${limitedValues.length} rows.`
        );

        return {
            ...editorSpec,
            data: {
                values: limitedValues,
            },
        };
    }

    return editorSpec;
}

export function ChartSpecModal({
    isOpen,
    onClose,
    chartSpec,
    vegaView,
    onApply,
    aiGeneratedSpec,
}: ChartSpecModalProps) {
    const [jsonText, setJsonText] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [hasChanges, setHasChanges] = useState(false);
    const [copyButtonText, setCopyButtonText] = useState('JSONをコピー');

    // Initialize JSON text when modal opens or chartSpec changes
    useEffect(() => {
        if (isOpen) {
            // Display spec with values hidden
            setJsonText(moveDataToEnd(chartSpec, true));
            setError(null);
            setHasChanges(false);
        }
    }, [isOpen, chartSpec]);

    const handleJsonChange = (newText: string) => {
        setJsonText(newText);
        setHasChanges(true);

        // Try to parse and validate
        try {
            JSON.parse(newText);
            setError(null);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Invalid JSON');
        }
    };

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(jsonText);
            setCopyButtonText('コピーしました！');
            setTimeout(() => {
                setCopyButtonText('JSONをコピー');
            }, 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
            setCopyButtonText('コピー失敗');
            setTimeout(() => {
                setCopyButtonText('JSONをコピー');
            }, 2000);
        }
    };

    const handleApply = () => {
        try {
            const parsedSpec = JSON.parse(jsonText);
            if (onApply) {
                onApply(parsedSpec);
                setHasChanges(false);
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Invalid JSON');
        }
    };

    const handleReset = () => {
        // Reset to AI generated spec if available, otherwise reset to current chartSpec
        const resetSpec = aiGeneratedSpec || chartSpec;
        setJsonText(moveDataToEnd(resetSpec, true));
        setError(null);
        setHasChanges(true); // Mark as changed if resetting to AI spec
    };

    const handleOpenInVegaEditor = () => {
        try {
            // Prepare spec with actual data for Vega Editor
            const editorSpec = prepareSpecForVegaEditor(chartSpec, vegaView);
            const specString = JSON.stringify(editorSpec);

            // Compress spec using LZ-String (same as Vega Editor uses)
            const compressed = LZString.compressToEncodedURIComponent(specString);
            const vegaEditorUrl = `https://vega.github.io/editor/#/url/vega-lite/${compressed}`;

            window.open(vegaEditorUrl, '_blank');
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Invalid JSON');
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === 'Tab') {
            e.preventDefault();
            const target = e.currentTarget;
            const start = target.selectionStart;
            const end = target.selectionEnd;
            const newText = jsonText.substring(0, start) + '  ' + jsonText.substring(end);
            setJsonText(newText);
            setHasChanges(true);
            // Set cursor position after the inserted spaces
            setTimeout(() => {
                target.selectionStart = target.selectionEnd = start + 2;
            }, 0);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[2000] flex items-center justify-center">
            <div className="absolute inset-0 bg-black/30" onClick={onClose} />
            <div className="relative bg-white rounded-lg shadow-xl max-w-4xl w-full mx-4 max-h-[80vh] flex flex-col">
                <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
                    <div>
                        <h3 className="text-lg font-semibold text-gray-900">グラフ仕様</h3>
                        {hasChanges && <p className="text-xs text-orange-600 mt-1">未保存の変更があります</p>}
                    </div>
                    <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
                        <svg
                            className="w-6 h-6"
                            fill="none"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                    </button>
                </div>

                <div className="flex-1 overflow-auto p-6">
                    <textarea
                        value={jsonText}
                        onChange={e => handleJsonChange(e.target.value)}
                        onKeyDown={handleKeyDown}
                        onClick={e => e.stopPropagation()}
                        onMouseDown={e => e.stopPropagation()}
                        className={`w-full h-full font-mono text-sm p-4 rounded-lg border resize-none ${
                            error
                                ? 'border-red-300 bg-red-50 focus:border-red-500 focus:ring-red-500'
                                : 'border-gray-300 bg-gray-50 focus:border-blue-500 focus:ring-blue-500'
                        }`}
                        style={{ minHeight: '400px' }}
                        spellCheck={false}
                        readOnly={false}
                    />
                    {error && (
                        <div className="mt-2 p-3 bg-red-100 border border-red-300 rounded-lg">
                            <p className="text-sm text-red-800 font-medium">検証エラー:</p>
                            <p className="text-xs text-red-700 mt-1">{error}</p>
                        </div>
                    )}
                </div>

                <div className="flex items-center justify-between px-6 py-4 border-t border-gray-200">
                    <div className="flex items-center gap-3">
                        {aiGeneratedSpec && (
                            <button
                                onClick={handleReset}
                                className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
                            >
                                リセット
                            </button>
                        )}
                    </div>
                    <div className="flex items-center gap-3">
                        <button
                            onClick={handleOpenInVegaEditor}
                            disabled={!!error}
                            className={`px-4 py-2 rounded-lg transition-colors ${
                                error
                                    ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                    : 'bg-green-600 text-white hover:bg-green-700'
                            }`}
                            title="Vegaエディタで開く"
                        >
                            Vegaエディタで開く
                        </button>
                        <button
                            onClick={handleCopy}
                            className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
                        >
                            {copyButtonText}
                        </button>
                        {onApply && (
                            <button
                                onClick={handleApply}
                                disabled={!!error || !hasChanges}
                                className={`px-4 py-2 rounded-lg transition-colors ${
                                    error || !hasChanges
                                        ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                        : 'bg-blue-600 text-white hover:bg-blue-700'
                                }`}
                            >
                                変更を適用
                            </button>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
