import type { TopLevelSpec } from 'vega-lite';

export interface ChartSpec {
    id: string;
    spec: VegaChartSpec;
    timestamp: Date;
    title?: string;
    aiGeneratedSpec?: VegaChartSpec; // Original spec generated by AI
}

export type VegaChartSpec = TopLevelSpec & {
    data?: TopLevelSpec['data'] & {
        sql?: string;
    };
};
